### ISSUE TITLE
[README] 회의 일정을 조정한다.

### ISSUE THREAD

**Issue by HelloMandu** [FUBAR-ORG/INVAIZ-Design-System#38]

**Comment by HelloMandu** [comment]
- 수요일: 21:30 ~ 22:30
- 일요일: 10:00 ~ 11:00

**Comment by IRONAGE-Park** [comment]
매주 수요일: 21시 30분 ~ 22시 30분
매주 일요일: 10시 00분 ~ 11시 00분

추후 일정 조정 가능함.
