### ISSUE TITLE
Github 이슈를 Slack으로 확인할 수 있다.

### ISSUE THREAD

**Issue by HelloMandu** [FUBAR-ORG/INVAIZ-Design-System#45]
## 목적 ❓

- Github 이슈, PR, 커밋 등을 Slack으로 확인할 수 있다.

## 설명 📝

- issues, pulls, commits, releases, deployments을 Slack에서 확인할 수 있도록 리포지토리와 연동했습니다.

**Comment by iwaskorean** [comment]
issues, pulls, commits, releases, deployments을 Slack에서 확인할 수 있도록 리포지토리와 연동했습니다.
