### ISSUE TITLE
[Process] Text- 텍스트 작업 완성되었습니다.

### ISSUE THREAD

**Issue by khGyun** [FUBAR-ORG/INVAIZ-Design-System#67]
- 텍스트가 완성되었으니 피그마 확인 후 피드백 부탁드립니다.
- 이슈 없으면 그대로 작업을 진행하셔도 됩니다.

**Comment by khGyun** [comment]
저번 회의에서 말씀한 key 값 수정완료 했습니다.
피드백 부탁드립니다!
@iwaskorean

**Comment by iwaskorean** [comment]
그대로 작업 진행하면 될 것 같습니다. 
고생하셨습니다 ~
@khGyun
