### ISSUE TITLE
[Bug] 폰트 파일이 storybook에서 적용되지 않습니다.

### ISSUE THREAD

**Issue by iwaskorean** [FUBAR-ORG/INVAIZ-Design-System#72]
## 설명

- `public/fonts` 디렉토리 내부의 폰트 파일이 storybook에서 적용되지 않습니다.

## 재현

- storybook config 파일 수정

```html
// .storybook/preview-head.html

<style>
  @font-face {
    font-family: 'INVAIZ';
    src: url('/fonts/INVAIZ.ttf') format('ttf');
    font-weight: normal;
  }
</style>
<script>
  window.global = window;
</script>
```

```js
// .storybook/main.js

...

module.exports = {
  ...
  staticDirs: ['../public'],
  ...
};
```

## 스크린샷

<img width="607" alt="스크린샷 2022-08-04 오후 10 05 19" src="https://user-images.githubusercontent.com/59280837/182854978-7ba345ee-a59c-4bcb-adeb-f43d79eab6f0.png">

## 환경

디바이스: 데스크탑[ v ] - 노트북[ ] - 패드[ ] - 모바일[ ]
운영체제: Windows[ ] - Mac [ v ]

**Comment by IRONAGE-Park** [comment]
`vite`의 엔트리 포인트 `/index.html`와 같이 바로 `link` 태그를 불러오면 어떤가요?

- `preview-head.html`

```html
<link rel="stylesheet" type="text/css" href="/stylesheets/font.css" />
<script>
  window.global = window;
</script>
```

**Comment by iwaskorean** [comment]
> `vite`의 엔트리 포인트 `/index.html`와 같이 바로 `link` 태그를 불러오면 어떤가요?
> 
> * `preview-head.html`
> 
> ```
> <link rel="stylesheet" type="text/css" href="/stylesheets/font.css" />
> <script>
>   window.global = window;
> </script>
> ```

폰트 파일에 꽂혀서 css 파일은 생각을 못했네요 ... 감사합니다 해결했습니다 .....
