### ISSUE TITLE
[Request] `SVG` 아이콘을 내보내기할 때 컬러를 용이하게 설정할 수 있도록 path로 변환한다.

### ISSUE THREAD

**Issue by IRONAGE-Park** [FUBAR-ORG/INVAIZ-Design-System#82]
## 설명

`SVG` 아이콘의 경우, `fill` 속성과 `stroke` 속성으로 컬러를 컨트롤할 수 있는데, 잘 구성되지 않은 요소에서 `fill`과 `stroke`를 무분별 하게 변경하면 아이콘이 깨지는 현상이 발생할 수 있습니다.
이에 `path` 요소를 통해 `SVG`를 구현하는 것이 좋을 것 같습니다.

## 작업 내용

1. `SVG` 파일의 내부 태그를 `path`로 구현한다.
2. 혹은 `path`로 변환한다.

**Comment by khGyun** [comment]
조사해본 결과 Copy as SVG를 통해 HTML 코드로 내보낼 수 있는 것 같습니다.

-  아이콘 선택 후 우클릭
![image](https://user-images.githubusercontent.com/109227210/185416341-c144b227-aebb-429d-ac05-952b754c77de.png)

- Copt/Paste as에 Copy as SCV 클릭
![image](https://user-images.githubusercontent.com/109227210/185416577-9fdd5ebe-20f5-4001-b91a-17dbf88fcb0a.png)

- 붙여넣기를 하면 아래와 같이 나옵니다.
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="12" fill="#1E212E"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.1133 3.6001C10.5414 3.6001 10.086 4.07885 10.1146 4.65004L10.6607 15.5731C10.6873 16.1053 11.1266 16.5232 11.6595 16.5232H12.3416C12.8745 16.5232 13.3137 16.1053 13.3403 15.5731L13.8865 4.65004C13.915 4.07885 13.4596 3.6001 12.8877 3.6001H11.1133ZM11.7084 17.8157C11.1561 17.8157 10.7084 18.2634 10.7084 18.8157V19.4003C10.7084 19.9526 11.1561 20.4003 11.7084 20.4003H12.293C12.8453 20.4003 13.293 19.9526 13.293 19.4003V18.8157C13.293 18.2634 12.8453 17.8157 12.293 17.8157H11.7084Z" fill="#F5F5F5"/>
</svg>

- 이렇게 하는 것이 맞는지 확인 부탁드립니다.
@IRONAGE-Park @HelloMandu

**Comment by IRONAGE-Park** [comment]
마 그라입시다.

**Comment by khGyun** [comment]
아이콘 전체 Stroke -> fill 속성으로 바꿨습니다.
아이콘 정리는 내일 중으로 하겠습니다
